# Generated by Django 3.1.7 on 2021-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_contact_self_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_ZIP',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_line1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_line2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
